UPGRADES = [
    {
        "id"          : "click_damage",
        "label"       : "Swordsmanship Mastery",
        "description" : "+1 damage per click",
        "base_cost"   : 25,
        "cost_growth" : 1.7,
        "effect"      : "click_damage",
        "effect_value": 1,
        "icon"        : "skill_swordsmanship.png",
        "min_floor"   : 0,
    },
    {
        "id"          : "crit_chance",
        "label"       : "Spot Weakness",
        "description" : "+1% critical hit chance",
        "base_cost"   : 35,
        "cost_growth" : 2.0,
        "effect"      : "crit_chance",
        "effect_value": 0.01,
        "icon"        : "skill_weakness_spot.png",
        "min_floor"   : 0,
    },
    {
        "id"          : "crit_multiplier",
        "label"       : "Berserker Rage",
        "description" : "+0.2x critical multiplier",
        "base_cost"   : 130,
        "cost_growth" : 1.99,
        "effect"      : "crit_multiplier",
        "effect_value": 0.3,
        "icon"        : "skill_critical_hit_amplifier.png",
        "min_floor"   : 0,
    },
    {
        "id"          : "gold_multiplier",
        "label"       : "Profit maker",
        "description" : "+0.2x Magic Stone rewards",
        "base_cost"   : 50,
        "cost_growth" : 2.0,
        "effect"      : "gold_multiplier",
        "effect_value": 0.2,
        "icon"        : "skill_profit_maker.png",
        "min_floor"   : 0,
    },
    {
        "id"          : "auto_dps",
        "label"       : "Fast Slash",
        "description" : "+2 damage per second (auto) | Unlocked after first boss",
        "base_cost"   : 300,
        "cost_growth" : 1.9,
        "effect"      : "auto_dps",
        "effect_value": 2,
        "icon"        : "skill_slashing_auto.png",
        "min_floor"   : 1,
    },

]

STATS_UPGRADES = [
    {
        "id"          : "strength",
        "label"       : "STR — Strength",
        "description" : "+1 STR — flat bonus to every hit",
        "base_cost"   : 100,
        "cost_growth" : 1.8,
        "effect"      : "strength",
        "effect_value": 1,
        "icon"        : "skill_strength.png",
        "min_floor"   : 0,
        "color"       : (220, 80, 80),    # rouge
    },
    {
        "id"          : "intelligence",
        "label"       : "INT — Intelligence",
        "description" : "+1 INT — multiplies damage via √INT",
        "base_cost"   : 150,
        "cost_growth" : 2.0,
        "effect"      : "intelligence",
        "effect_value": 1,
        "icon"        : "skill_intelligence.png",
        "min_floor"   : 0,
        "color"       : (80, 120, 220),   # bleu
    },
    {
        "id"          : "endurance",
        "label"       : "END — Endurance",
        "description" : "+1 END — increases endurance bar by 10",
        "base_cost"   : 120,
        "cost_growth" : 1.9,
        "effect"      : "endurance",
        "effect_value": 1,
        "icon"        : "skill_endurance.png",
        "min_floor"   : 0,
        "color"       : (80, 200, 120),   # vert
    },
]